version: '3.3'

services:
  test_app:
    build: .
    ports:
      - "8080:8000"
    volumes:
      - ./:/app/
    depends_on:
      test_db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=test_db
    user: ${MY_UID}
  test_db:
    image: postgres:15.0-alpine
    env_file:
      - .env
    environment:
      - INSTALL_DEV=True
    expose:
      - 5432
    volumes:
      - test_postgres:/var/lib/postgresql/data
      - ./scripts/create_test_db.sh:/docker-entrypoint-initdb.d/create_test_db.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  test_postgres: