"""added chain between media and twit

Revision ID: 921ddc186ae8
Revises: 4c1723e0c7b6
Create Date: 2023-03-08 19:44:07.352306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921ddc186ae8'
down_revision = '4c1723e0c7b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mediatwit',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('twit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['twit_id'], ['twit.id'], ),
    sa.PrimaryKeyConstraint('media_id', 'twit_id')
    )
    op.create_index(op.f('ix_mediatwit_media_id'), 'mediatwit', ['media_id'], unique=False)
    op.create_index(op.f('ix_mediatwit_twit_id'), 'mediatwit', ['twit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mediatwit_twit_id'), table_name='mediatwit')
    op.drop_index(op.f('ix_mediatwit_media_id'), table_name='mediatwit')
    op.drop_table('mediatwit')
    # ### end Alembic commands ###
