"""init

Revision ID: 2d33c5bdfad7
Revises: 
Create Date: 2023-03-09 23:14:46.491735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d33c5bdfad7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='user_key_unique')
    )
    op.create_table('twit',
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('tweet_data', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('tweet_id'),
    sa.UniqueConstraint('tweet_id')
    )
    op.create_table('mediatwit',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['twit.tweet_id'], ),
    sa.PrimaryKeyConstraint('media_id', 'tweet_id')
    )
    op.create_index(op.f('ix_mediatwit_media_id'), 'mediatwit', ['media_id'], unique=False)
    op.create_index(op.f('ix_mediatwit_tweet_id'), 'mediatwit', ['tweet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mediatwit_tweet_id'), table_name='mediatwit')
    op.drop_index(op.f('ix_mediatwit_media_id'), table_name='mediatwit')
    op.drop_table('mediatwit')
    op.drop_table('twit')
    op.drop_table('user')
    op.drop_table('media')
    # ### end Alembic commands ###
