"""follower

Revision ID: 9065c8b0f388
Revises: c2cf0d3ec332
Create Date: 2023-03-12 16:43:03.642245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9065c8b0f388'
down_revision = 'c2cf0d3ec332'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'following_id')
    )
    op.create_index(op.f('ix_follow_follower_id'), 'follow', ['follower_id'], unique=False)
    op.create_index(op.f('ix_follow_following_id'), 'follow', ['following_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_follow_following_id'), table_name='follow')
    op.drop_index(op.f('ix_follow_follower_id'), table_name='follow')
    op.drop_table('follow')
    # ### end Alembic commands ###
