"""remove user from media

Revision ID: a07cd9063138
Revises: 921ddc186ae8
Create Date: 2023-03-08 21:34:09.972743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07cd9063138'
down_revision = '921ddc186ae8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('media_user_id_fkey', 'media', type_='foreignkey')
    op.drop_column('media', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('media_user_id_fkey', 'media', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
