"""twit

Revision ID: 302cc3394fd8
Revises: dc7984d0affb
Create Date: 2023-02-19 18:29:42.678178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302cc3394fd8'
down_revision = 'dc7984d0affb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('twit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twit')
    # ### end Alembic commands ###
